/** Dados estáticos — Figma Operador Dashboard (nó 23:1864). */

export const MOCK_OPERATOR_NAME = 'Luís Pedro'

export const MOCK_OPERATOR_STATS = {
  recolhasHoje: 3,
  recolhasAgendadas: 9,
  contentoresAtivos: 2,
  kmPercorridos: '34',
}

export const MOCK_DAY_COLLECTIONS = [
  {
    id: 'COL-001',
    clienteLabel: 'Revigrés',
    locationDetail: 'Polo 4 - Aveiro',
    status: 'hoje',
    scheduledAt: '06/06/2026 10:00',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-002',
    clienteLabel: 'Revigrés',
    locationDetail: 'Sede - Águeda',
    status: 'hoje',
    scheduledAt: '06/06/2026 10:00',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-003',
    clienteLabel: 'C.M Águeda',
    locationDetail: 'R. 5 de Outubro',
    status: 'hoje',
    scheduledAt: '06/06/2026 10:00',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-004',
    clienteLabel: 'Ramalhos',
    locationDetail: 'Sede - Águeda',
    status: 'hoje',
    scheduledAt: '06/06/2026 10:00',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-005',
    clienteLabel: 'J.F Valongo do Vouga',
    locationDetail: 'Junta de Freguesia',
    status: 'hoje',
    scheduledAt: '06/06/2026 10:00',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-006',
    clienteLabel: 'E.S Castilho',
    locationDetail: 'E.S Castilho - Águeda',
    status: 'hoje',
    scheduledAt: '06/06/2026 10:00',
    binNumber: '20',
    taskType: 'recolher',
  },
]

export const MOCK_UPCOMING_COLLECTIONS = [
  {
    id: 'COL-007',
    clienteLabel: 'C.M Águeda',
    locationDetail: 'Praça do Município',
    status: 'amanha',
    scheduledAt: '07/06/2026 09:00',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-008',
    clienteLabel: 'C.M Águeda',
    locationDetail: 'Largo Dr. João de Barros',
    status: 'amanha',
    scheduledAt: '07/06/2026 09:45',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-009',
    clienteLabel: 'Ramalhos',
    locationDetail: 'Zona Industrial',
    status: 'amanha',
    scheduledAt: '07/06/2026 10:15',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-010',
    clienteLabel: 'Revigrés',
    locationDetail: 'Polo 4 - Aveiro',
    status: 'agendada',
    scheduledAt: '08/06/2026 09:00',
    binNumber: '20',
    taskType: 'recolher',
  },
  {
    id: 'COL-011',
    clienteLabel: 'Revigrés',
    locationDetail: 'Sede - Águeda',
    status: 'agendada',
    scheduledAt: '08/06/2026 10:00',
    binNumber: '20',
    taskType: 'recolher',
  },
]

export const MOCK_OPERATOR_HISTORICO = [
  {
    id: 'CNT-004',
    clienteLabel: 'Revigrés',
    locationPrefix: 'Polo 4',
    locationDetail: 'Aveiro',
    status: 'finalizado',
    historicoScheduledAt: '18/07/2026 11:40',
    scheduledAt: '18/07/2026 11:40',
    binNumber: '02',
    taskType: 'recolher',
    estado: 'concluido',
    estadoKey: 'concluido',
    dataIso: '2026-07-18',
    dateSortValue: new Date('2026-07-18').getTime(),
  },
  {
    id: 'CNT-005',
    clienteLabel: 'C.M Águeda',
    locationPrefix: 'Praça do Município',
    locationDetail: 'Águeda',
    status: 'finalizado',
    historicoScheduledAt: '17/07/2026 09:15',
    scheduledAt: '17/07/2026 09:15',
    binNumber: '01',
    taskType: 'entregar',
    estado: 'concluido',
    estadoKey: 'concluido',
    dataIso: '2026-07-17',
    dateSortValue: new Date('2026-07-17').getTime(),
  },
]
